spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?useAffectedRows=true
    username: root
    password: /*1Univ2mysql*/

# 控制台打印出sql语句，开发时可用
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置mapper xml的扫描路径
  mapper-locations: classpath:mapper/*.xml
